import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'

import '~/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: '#D9264A',
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <div className="grid grid-cols-5 place-items-stretch h-[100dvh]">
            <main className="col-span-3 flex items-center justify-center">
              {children}
            </main>
            <div className="col-span-2 overflow-hidden bg-unsplash-random bg-center bg-cover"></div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
